### ISSUE TITLE
Multiple-Stream Fusion module 

### ISSUE THREAD

**Issue by dashangyanhua** [hulianyuyy/DSTA-SLR#5]
Thank you very much for your code! Excellent work!
I am a beginner who is just starting to learn this field. I saw that you mentioned the Multiple-Stream Fusion Module in your article, but I couldn't find the relevant module location. Could you please tell me where it is? thank you!

**Comment by hulianyuyy** [comment]
I forgot to add the ensembling part in the introduction part about how to perform multi-stream fusing and now have added it. You may currently follow it to perform fusion.

**Comment by dashangyanhua** [comment]
Thank you very much for your prompt and accurate reply! I was under the impression that the processing was done within the model, rather than using the trained parameters, and it had been bothering me for a long time. Your explanation has been very helpful to me!

**Comment by hulianyuyy** [comment]
You are welcome. Feel free to contact me if you have further questions.
